name: Robot Framework

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports

  generate_report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
